# Generated by Django 4.1.3 on 2023-02-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heropy.book')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('dexterity', models.IntegerField(default=1)),
                ('endurance', models.IntegerField(default=1)),
                ('luck', models.IntegerField(default=1)),
                ('magic', models.IntegerField(default=1)),
                ('gold', models.IntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heropy.book')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMagic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('effect', models.CharField(max_length=24)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heropy.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('effect', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], default='add', max_length=24)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heropy.player')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_dest_number', models.IntegerField(default=0)),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='heropy.bookchapter')),
            ],
        ),
    ]
